### ISSUE TITLE
Texte ändern

### ISSUE THREAD

**Issue by Schmidty2** [alnv/catalog-manager-wishlist#1]
Hallo,
Danke für die tolle Erweiterung Wishlist.

Ist es möglich, die Texte „Zur Wunschliste hinzufügen“ und „Aus der Wunschliste entfernen“ zu ändern bzw. variabel zu gestalten? Bei der Frontend-Tabellenausgabe sollte auch auch der Text in der Kopfzeile der entsprechenden Spalte variabel sein.
Es wäre toll, wenn dafür drei Textfelder bei der Wunschlistenkonfiguration hinzugefügt werden könnten.
In meinem Einsatzfall bräuchte ich die Texte „Auf die Merkliste setzen“ und „Von der Merkliste entfernen“, die Kopfzeile bei der Tabellenausgabe soll das Wort „Merkliste“ enthalten.

Danke.

**Comment by alnv** [comment]
Hierfür stehen dir folgende Variablen zur Verfügung:

```
$GLOBALS['TL_LANG']['MSC']['CATALOG_MANAGER']['wishlist'] = 'Wunschliste';
$GLOBALS['TL_LANG']['MSC']['CATALOG_MANAGER']['wishlistAmount'] = 'Anzahl';
$GLOBALS['TL_LANG']['MSC']['CATALOG_MANAGER']['wishlistUpdateButton'] = 'Anzahl ändern';
$GLOBALS['TL_LANG']['MSC']['CATALOG_MANAGER']['wishlistAddButton'] = 'Zur Wunschliste hinzufügen';
$GLOBALS['TL_LANG']['MSC']['CATALOG_MANAGER']['wishlistDeleteButton'] = 'Aus der Wunschliste entfernen';
```
