### ISSUE TITLE
Inserttag {{WISHLIST_AMOUNT::ctlg_product}} immer 0

### ISSUE THREAD

**Issue by saress** [alnv/catalog-manager-wishlist#11]
Hallo,

der Insert-Tag {{WISHLIST_AMOUNT::ctlg_product}} liefert als Ergebnis immer 0 zurück.

In der Datei: WishlistInserttag.php liefert die Zeile 57:

`$arrTables = $objSession->get( 'wishlist_tables' );`

immer NULL zurück, keine Ahnung warum, aber vermutlich ist das das Problem.

Beste Grüße
Sares

**Comment by alnv** [comment]
welche Version catalog-manager-wishlist läuft bei dir?

**Comment by saress** [comment]
Das Projekt läuft unter Contao 4.9.12, CM 1.31.41 und Wishlist 2.2.3.

Beste Grüße 
Sares

**Comment by alnv** [comment]
Versuch es mal mit Wishlist 2.2.4.

**Comment by saress** [comment]
Hallo Alexander,

vielen Dank, das schaut sehr gut aus und die Anzahl der abgelegten Produkte wird jetzt angezeigt :-)

Herzlichen Dank und beste Grüße
Sares
