### ISSUE TITLE
Einzelne Wishlist Variablen in Notification Center für E-Mail Versand auslesen

### ISSUE THREAD

**Issue by mueller-upbits** [alnv/catalog-manager-wishlist#14]
Hallo zusammen,
kann ich im Notification Center einzelne Variablen meiner Catalog Tabelle aus der Wunschliste auslesen.
Ich habe eine Tabelle:
Artikel-NR - Bezeichnung - Interne Nr

An den Endkunden möchte ich eine Mail versenden mit
Artikel-Nr + Bezeichnung
And Interne Mitarbeiter möchte ich eine Mail versenden mit:
Artikel-NR - Bezeichnung - Interne Nr

aktuell kann ich nur {WISHLIST} verwenden und da in diesem Template kann ich es nur "global" einstellen.
Somit kann ich dem Kunden die Interne Nr nicht "verheimlichen"

VG
Marcel

**Comment by akroii** [comment]
@alnv man bräcuhte praktisch die Möglichkeit ein eigenes Template für den InsertTag {{WISHLIST}} anzugeben

**Comment by alnv** [comment]
Ab v2.2.6 kann man das gewünschte Template im Inserttag übergeben z.B. {{WISHLIST::::?template=wishlist_view}}
