### ISSUE TITLE
Wunschliste wird bei bearbeiteten Template nicht angezeigt

### ISSUE THREAD

**Issue by seibtph** [alnv/catalog-manager-wishlist#2]
Ich habe das Template ctlg_view_teaser.html5 angepasst und wollte nun die Wunschliste integrieren. Mein Problem ist, dass die Wunschliste nur angezeigt wird, wenn man kein individuelles Template in der Listenansicht auswählt. Sobald ich das Template ctlg_view_teaser.html5 anlege, ist die Wunschliste nicht mehr sichtbar.

Der Grund warum ich das Template angepasst habe war, weil ich in der Listenansicht nicht alle Felder anzeigen wollte. Erst in der Detailansicht sollen alle Felder angezeigt werden. Mit dem Listenansicht-Modul geht das anscheinend nicht einzustellen oder?

**Comment by alnv** [comment]
Für die Ausgabe ist dieser Block zuständig:

``` html
<?php if ( $this->useWishlist ): ?>
        <div class="wishlist">
            <form method="GET" enctype="application/x-www-form-urlencoded">
                <input type="hidden" name="wishlist_id" value="<?= $this->id ?>">
                <input type="hidden" name="wishlist_type" value="add_to_wishlist">
                <?php if ( $this->wishlistAmount ): ?>
                    <div class="widget widget-text">
                        <label for="wishlist_id_<?= $intIndex ?>_amount"><?= $this->wishlistAmountLabel ?></label>
                        <input type="text" class="text" placeholder="<?= $this->wishlistAmountLabel ?>" name="wishlist_amount" id="wishlist_id_<?= $intIndex ?>_amount" value="<?= $this->wishlistAmountValue ?>">
                    </div>
                <?php endif; ?>

                <?php if ( $this->wishlistAddButton ): ?>
                    <div class="widget widget-submit">
                        <button type="submit" class="submit wishlist-add-button <?= ( $this->isInWishlist ? 'wishlist-update-button' : '' ) ?>"><?= $this->wishlistAddButtonLabel ?></button>
                    </div>
                <?php endif; ?>
            </form>
            <?php if ( !$this->wishlistDisableRemoveButton && $this->isInWishlist ): ?>
                <form method="GET" enctype="application/x-www-form-urlencoded">
                    <input type="hidden" name="wishlist_id" value="<?= $this->id ?>">
                    <input type="hidden" name="wishlist_type" value="remove_from_wishlist">
                    <input type="hidden" name="wishlist_table" value="<?= $this->wishlistTable ?>">
                    <div class="widget widget-submit">
                        <button type="submit" class="submit wishlist-remove-button"><?= $this->wishlistAddDeleteLabel ?></button>
                    </div>
                </form>
            <?php endif; ?>
        </div>
    <?php endif; ?>
```

Du kannst es einfach in dein angepasstes Template hinzufügen. Am besten ist es auch wenn mein sein angepasstes Template umbenennt z.B _ctlg_view_teaser_custom_ o.ä

**Comment by seibtph** [comment]
Dankeschön, das hat schonmal geklappt.

Allerdings habe ich noch einen Fehler, wenn ich mehr als ein Produkt zur Wunschliste hinzufüge. Bei nur einem Produkt funktioniert alles wunderbar. Ich nutze Contao 4.4.18.

Folgender Fehler tritt auf: 
`An exception occurred. {"exception":"[object] (Exception(code: 0): Too few arguments to build the query string at ***/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:303)"} []`

Ich habe die Schritte in der Dokumentation befolgt.

**Comment by alnv** [comment]
Mit der neuesten Catalog Manager Version ( v1.22-beta.1 ) soll es funktionieren.

**Comment by seibtph** [comment]
Danke, der Fehler ist behoben. :)
