### ISSUE TITLE
Ändern eines DB Eintrages nach Absender der Merkliste

### ISSUE THREAD

**Issue by mueller-steinhauer** [alnv/catalog-manager-wishlist#3]
Hallo,

ich habe die Erweiterung jetzt in meinem Template übernommen und kann die Merkliste verwenden.
Bei mir sind es Paletten die vermerkt werden können, diese haben einen Status: Verfügbar und abgerufen.

Gibt es die Möglichkeit diesen Status nach dem Versenden von Verfügbar auf abgerufen umzustellen ?

VG 
Marcel

**Comment by alnv** [comment]
Ich könnte dir ein Hook zur verfügung stellen. Mit dem du dein Status per Script steuern könntest.

**Comment by mueller-steinhauer** [comment]
Das hört sich gut an, mein Kollege Torsten hier bitkorn meldet sich gleich ;-)

Muss echt sagen die Erweiterung ist richtig gut, und benötigt nicht ganz so viel Einarbeitung wie MetaModells

**Comment by alnv** [comment]
Wenn du "Notification Center" im Einsatz hast, kannst du den "sendNotificationMessage" Hook verwenden.

Die ID der Datensätze findest du in der Session:

``` php
$objSession = \Session::getInstance();
$arrIDs = $objSession->get( 'wishlist_tables' );
```

Damit hättest du alles was du benötigst…

**Comment by alnv** [comment]
Übrigens wäre auch ein Reset Funktion möglich… Einfach "wishlist_tables" Eintrag bei der Session löschen.

**Comment by mueller-steinhauer** [comment]
Ok vielen Dank, das Notification Center habe ich schon eingebunden, ich versuch es mal
