### ISSUE TITLE
Fehlermeldung beim Versenden der Wunschliste bei mehreren Einträgen

### ISSUE THREAD

**Issue by seibtph** [alnv/catalog-manager-wishlist#5]
Ich würde im Notification Center gern den Insert Tag {{WISHLIST}} verwenden. Wenn nur ein Eintrag vorhanden ist funktioniert das ganze auch prima. Bei mehreren Einträgen kommt bei mir allerdings folgender Fehler:

app.CRITICAL: An exception occurred. {"exception":"[object] (Exception(code: 0): Too few arguments to build the query string at /www/htdocs/***/***/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:303)"} []

Über Hilfe wie dieser Fehler behoben werden kann wäre ich sehr dankbar.

**Comment by alnv** [comment]
Welche Catalog Manager Version läuft bei dir?

**Comment by alnv** [comment]
Ich denke ein Update auf aktuellste Version sollte es beheben. Siehe #4
