### ISSUE TITLE
Wunschliste wird beim Neuladen der Seite nicht gespeichert

### ISSUE THREAD

**Issue by mueller-upbits** [alnv/catalog-manager-wishlist#8]
Ich habe hier eine Tabelle mit Daten "Paletten" jetzt klicke ich auf zur Wunschliste hinzufügen und er zeigt mit auch direkt an Aus der Wunschliste entfernen. 

Jetzt ist aber das Problem das beim Seiten Neuladen die Daten weg sind und ich auch über { { WISHLIST } } die Daten nicht auslesen kann.

Meine Settings sind Contao 4.9. Gibt es da evtl einen Bug ?

![Bildschirmfoto 2020-05-12 um 09 06 20](https://user-images.githubusercontent.com/61277590/81648987-e552bd00-942f-11ea-9a6e-1898fdde29dc.png)

**Comment by upbits-holding** [comment]
Eine weitere Info hierzu.

Wenn ich nicht als User im Frontend Angemeldet bin funktioniert es. Melde ich mich an im Frontend so tritt das oben beschriebene Problem auf.

**Comment by alnv** [comment]
Ein Bug konnte ich nicht feststellen. Versuch's mal mit einem anderem Browser.

**Comment by upbits-holding** [comment]
Das habe ich auch schon alles versucht. Auch ein anderer User bringt nix.
Wir die Merkliste in der DB gespeichert oder in einer Session / cookie etc. ?

Die Funktion ist für mich sehr wichtig da ich darüber eine art Bestellsystem erstellen möchte.
Könntest du dir das Alternativ mal ansehen ?

**Comment by alnv** [comment]
Die Einträge werden in einer Session Variable gespeichert.
Gerne über: https://catalog-manager.org/support-ticket.html
